openapi: 3.0.4

info:
  title: AlgaShop - Ordering
  version: "1.0.0"

servers:
  - description: Development
    url: "http://localhost:8080"
  - description: Production
    url: "http://api.algashop.com"

paths:
  /api/v1/customers:
    post:
      description: Register new customer
      tags:
        - Customers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CustomerInput"
      responses:
        201:
          description: Customer created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Customer"
          headers:
            Location:
              schema:
                type: string
              description: Resource Address
              example: "/api/v1/customers/d9c5d7ab-819d-41b4-a11b-04d83effe362"
        400:
          $ref: "#/components/responses/BadRequest"
        409:
          $ref: "#/components/responses/Conflict"
        422:
          $ref: "#/components/responses/UnprecessableEntity"
        500:
          $ref: "#/components/responses/InternalError"
    get:
      description: List customers
      tags:
        - Customers
      parameters:
        - schema:
            type: string
            example: "12345"
          in: query
          name: document
          required: false
        - schema:
            type: string
            example: "johndoe@email.com"
          in: query
          name: email
          required: false
        - $ref: "#/components/parameters/page"
        - $ref: "#/components/parameters/size"
        - $ref: "#/components/parameters/sort"
        - $ref: "#/components/parameters/direction"
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/Page"
                  - type: object
                properties:
                  content:
                    type: array
                    items:
                      $ref: "#/components/schemas/CustomerSummary"
  /api/v1/customers/{customerId}:
    get:
      parameters:
        - schema:
            type: string
          name: customerId
          in: path
          required: true
          example: 'd9c5d7ab-819d-41b4-a11b-04d83effe362'
      description: Get one customer by id
      tags:
        - Customers
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        404:
          $ref: "#/components/responses/NotFound"
    put:
      parameters:
        - schema:
            type: string
          name: customerId
          in: path
          required: true
          example: 'd9c5d7ab-819d-41b4-a11b-04d83effe362'
      description: Edit Customer
      tags:
        - Customers
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CustomerInput"
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        400:
          $ref: "#/components/responses/BadRequest"
        404:
          $ref: "#/components/responses/NotFound"
        409:
          $ref: "#/components/responses/Conflict"
        422:
          $ref: "#/components/responses/UnprecessableEntity"
        500:
          $ref: "#/components/responses/InternalError"
    delete:
      parameters:
        - schema:
            type: string
          name: customerId
          in: path
          required: true
          example: 'd9c5d7ab-819d-41b4-a11b-04d83effe362'
      description: Delete Customer
      tags:
        - Customers
      responses:
        204:
          description: No content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        404:
          $ref: "#/components/responses/NotFound"
components:
  parameters:
    page:
      schema:
        type: integer
        example: 0
      name: page
      in: query
      required: true
    size:
      schema:
        type: integer
        example: 5
      name: size
      in: query
      required: false 
    sort:
      schema:
        type: string
        example: "firstName"
      name: sortByProperty
      in: query
      required: false 
    direction:
      schema:
        type: string
        example: "desc"
      name: sortDirection
      in: query
      required: false
  responses:
    NotFound:
      description: Resource not found
      content: 
        application/problem+json:
          schema:
            $ref: "#/components/schemas/ProblemDetail"
    BadRequest:
      description: Invalid request
      content: 
        application/problem+json:
          schema:
            $ref: "#/components/schemas/ProblemDetail"
    Conflict:
      description: Conflict resource
      content: 
        application/problem+json:
          schema:
            $ref: "#/components/schemas/ProblemDetail"
    UnprecessableEntity:
      description: Unprecessable Entity
      content: 
        application/problem+json:
          schema:
            $ref: "#/components/schemas/ProblemDetail"
    InternalError:
      description: Internal Server Error
      content: 
        application/problem+json:
          schema:
            $ref: "#/components/schemas/ProblemDetail"
  schemas:
    Customer:
      type: object
      required:
        - id
        - firstName
        - lastName
        - email
        - document
        - phone
        - birthDate
        - loayaltyPoints
        - registeredAt
        - archivedAt
        - promotionNotificationsAllowed
        - archived
        - address
      properties:
        id:
          type: string
          example: 'd9c5d7ab-819d-41b4-a11b-04d83effe362'
        firstName:
          type: string
          example: "Jonh"
        lastName:
          type: string
          example: "Doe"
        email:
          type: string
          example: "johndoe@email.com"
        document:
          type: string
          example: "123456"
        phone:
          type: string
          example: "11999999999"
        birthDate:
          type: string
          format: date
          example: "1999-07-23"
        loayaltyPoints:
          type: number
          example: 10
        registeredAt:
          type: string
          format: date
          example: "1999-07-23T00:00:00Z"
        archivedAt:
          type: string
          format: date
          example: "1999-07-23T00:00:00Z"
        promotionNotificationsAllowed:
          type: boolean
          example: false
        archived:
          type: boolean
          example: false
    Address:
      type: object
      required:
        - street
        - number
        - complement
        - neighbourhood
        - city
        - state
        - zipCode
      properties:
        street:
          type: string
          example: "Bourbon Street"
          nullable: false
          x-validation: "notBlank"
        number:
          type: string
          example: "2000"
          nullable: false
          x-validation: "notBlank"
        complement:
          type: string
          example: "apt 122"
          nullable: true
        neighbourhood:
          type: string
          example: "North Ville"
          nullable: false
          x-validation: "notBlank"
        city:
          type: string
          example: "Yostfort"
          nullable: false
          x-validation: "notBlank"
        state:
          type: string
          example: "South Carol"
          nullable: false
          x-validation: "notBlank"
    CustomerSummary:
      type: object
      required:
        - id
        - firstName
        - lastName
        - email
        - phone
        - archived
      properties:
        id:
          type: string
          example: 'd9c5d7ab-819d-41b4-a11b-04d83effe362'
        firstName:
          type: string
          example: "Jonh"
        lastName:
          type: string
          example: "Doe"
        email:
          type: string
          example: "johndoe@email.com"
        phone:
          type: string
          example: "11999999999"
        archived:
          type: boolean
          example: false
    CustomerInput:
      type: object
      required:
        - firstName
        - lastName
        - email
        - document
        - phone
        - birthDate
        - promotionNotificationsAllowed
        - address
      properties:
        firstName:
          type: string
          example: "Jonh"
          nullable: false
          x-validation: "notBlank"
        lastName:
          type: string
          example: "Doe"
          nullable: false
          x-validation: "notBlank"
        email:
          type: string
          example: "johndoe@email.com"
          nullable: false
          x-validation: ["email", "notBlank"]
        document:
          type: string
          example: "123456"
          nullable: false
          x-validation: "notBlank"
        phone:
          type: string
          example: "11999999999"
          nullable: false
          x-validation: "notBlank"
        birthDate:
          type: string
          format: date
          example: "1999-07-23"
          nullable: false
          x-validation: "pastDate"
        promotionNotificationsAllowed:
          type: boolean
          example: false
          nullable: false
        address:
          $ref: '#/components/schemas/Address'
    CustomerUpdateInput:
      type: object
      required:
        - firstName
        - lastName
        - phone
        - promotionNotificationsAllowed
        - address
      properties:
        firstName:
          type: string
          example: "Jonh"
          nullable: false
          x-validation: "notBlank"
        lastName:
          type: string
          example: "Doe"
          nullable: false
          x-validation: "notBlank"
        phone:
          type: string
          example: "11999999999"
          nullable: false
          x-validation: "notBlank"
        promotionNotificationsAllowed:
          type: boolean
          example: false
          nullable: false
        address:
          $ref: '#/components/schemas/Address'
          nullable: false
    ProblemDetail:
      type: object
      required:
        - status
        - type
      properties:
        status:
          type: integer
          example: 400
        type:
          type: string
          example: "/errors/invalid-data"
        title:
          type: string
          example: Invalid fields
        instance:
          type: string
          example: /"api/v1/customers"
        detail:
          type: string
          example: One or more fields are invalid
        fields:
          type: object
          example: Fields that caused the error
    Page:
      type: object
      required:
        - number
        - size
        - totalPages
        - totalElements
        - content
      properties:
        number:
          type: integer
          example: 2
        size:
          type: integer
          example: 9
        totalPages:
          type: integer
          example: 15
        totalElements:
          type: integer
          example: 150