asyncapi: 3.1.0

info:
  title: AlgaShop - Product Catalog AsyncAPI
  version: "1.0"

servers:
  development:
    host: "algashop-kafka-1:9092"
    protocol: kafka
    description: Development

channels:
  productEvents:
    address: product-catalog.product.events
    title: Product Events
    messages:
      productAdded:
        $ref: "#/components/messages/ProductAddedEvent"
      productPriceChanged:
        $ref: "#/components/messages/ProductPriceChangedEvent"
      productPriceChangedV2:
        $ref: "#/components/messages/ProductPriceChangedEventV2"
    bindings:
      kafka:
        topic: product-catalog.product.events
        partitions: 3
        replicas: 3
        topicConfiguration:
          min.insync.replicas: 2
        bindingVersion: "0.5.0"

operations:
  sendProductEvents:
    action: send # Producer
    channel:
      $ref: "#/channels/productEvents"
    summary: Publishes product events
    tags:
      - name: Products
    messages:
      - $ref: "#/channels/productEvents/messages/productAdded"
      - $ref: "#/channels/productEvents/messages/productPriceChanged"
      - $ref: "#/channels/productEvents/messages/productPriceChangedV2"

components:
  messages:
    ProductAddedEvent:
      name: ProductAddedEvent
      title: Product Added Event
      summary: Published when a new product is added.
      contentType: application/json
      tags:
        - name: Products
      payload:
        type: object
        required:
          - productId
          - addedAt
        properties:
          productId:
            $ref: "#/components/schemas/ProductId"
          addedAt:
            type: string
            format: date-time
            description: Date and time when a product was added.
      headers:
        type: object
        required:
          - __TypeId__
        properties:
          __TypeId__:
            type: string
            const: "ProductCatalog.ProductAddedIntegrationEvent"
            description: Type of the event for deserialization
      traits:
        - $ref: "#/components/messageTraits/KafkaProductKey"
    ProductPriceChangedEvent:
      name: ProductPriceChangedEvent
      title: Product Price Changed Event
      deprecated: true
      contentType: application/json
      tags:
        - name: Products
      headers:
        type: object
        required:
          - __TypeId__
        properties:
          __TypeId__:
            type: string
            const: "ProductCatalog.ProductPriceChangedEventIntegrationEvent"
      payload:
        type: object
        deprecated: true
        required:
          - productId
          - changedAt
        properties:
          productId:
            $ref: "#/components/schemas/ProductId"
          changedAt:
            type: string
            format: date-time
            example: "2024-04-04T00:12:45Z"
      traits:
        - $ref: "#/components/messageTraits/KafkaProductKey"
    ProductPriceChangedEventV2:
      name: ProductPriceChangedEventV2
      title: Product Price Changed Event (v2)
      contentType: application/json
      tags:
        - name: Products
      headers:
        type: object
        required:
          - __TypeId__
        properties:
          __TypeId__:
            type: string
            const: "ProductCatalog.ProductPriceChangedEventV2IntegrationEvent"
      payload:
        type: object
        required:
          - productId
          - changedAt
          - oldRegularPrice
          - oldSalePrice
          - newRegularPrice
          - newSalePrice
        properties:
          productId:
            $ref: "#/components/schemas/ProductId"
          changedAt:
            type: string
            format: date-time
            example: "2024-04-04T00:12:45Z"
          oldRegularPrice:
            $ref: "#/components/schemas/Money"
          oldSalePrice:
            $ref: "#/components/schemas/Money"
          newRegularPrice:
            $ref: "#/components/schemas/Money"
          newSalePrice:
            $ref: "#/components/schemas/Money"
      traits:
        - $ref: "#/components/messageTraits/KafkaProductKey"

  schemas:
    ProductId:
      type: string
      description: ID of product
      example: "fcc2897f-70a8-4c87-a4d0-26a4e0bb36dc"
    Money:
      type: number
      format: double
      example: 24.99

  messageTraits:
    KafkaProductKey:
      bindings:
        kafka:
          key:
            type: string
            description: Product id
            example: "fcc2897f-70a8-4c87-a4d0-26a4e0bb36dc"
          bindingVersion: "0.5.0"
